---
title: "case-study"
author: "Yang Gao"
date: "10/14/2021"
output: github_document
---


```{r}
library(tidyverse)
library(p8105.datasets)
library(leaflet)
```

## load a dataset
```{r}
data(nyc_airbnb)
```

questions wanna ask
*How many rentals are there? Of what type? In what places?
*Is price correlated with review score?
*Which neighbarhood is most popular? Most expensive?
*Is availability related to price?
*Is room type related to neighbarhood?
*Is length of stay related to neighborhaood group?

```{r}
nyc_airbnb %>% 
  mutate(stars = review_scores_location/2) %>% 
  rename(borough = neighbourhood_group)

```

```{r}
nyc_airbnb %>% 
  ggplot (aes(x=minimum_nights, y=price, color = neighbourhood_group)) +geom_point()
```

```{r}
nyc_airbnb %>% 
  ggplot (aes(y=price, x=availability_365, color = neighbourhood_group)) +geom_point() +
  facet_grid(.~ neighbourhood_group)
```




count
```{r}
nyc_airbnb %>% 
 janitor :: tabyl (borough, room_type)
```

```{r}
nyc_airbnb %>% 
  count (borough, room_type) %>% 
  pivot_wider()
```



```{r}
nyc_airbnb %>% 
  ggplot (aes(x=stars, y =price))+ geom_point()
```


```{r}
nyc_airbnb %>% 
  group_by (neighbourhood) %>% 
  summarize (mean_price = mean(price, na.rm = TRUE)) %>% 
  arrange(mean_price)

nyc_airbnb %>% 
  filter (neighbourhood_group == "Manhattan", price <= 1000 )%>% 
  mutate (neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  ggplot (aes (x= neighbourhood, y=price)) +geom_boxplot() +coord_flip() +facet_grid(.~ room_type)
```

Price vs Location
```{r}
nyc_airbnb %>% 
  sample_n (5000) %>% 
  ggplot (aes(x=lat , y=long, color = price)) +geom_point(alpha=0.5)
```


## mapping
```{r}
pal= colorNumeric ("Viridis", NULL)
nyc_airbnb %>% 
  sample_n(1000) %>% 
  leaflet() %>% 
  addTiles() %>% 
addCircleMarkers(~lat, ~long, radius = 1, color=~pal(price))
```














